[theme]
background = "1e1e1e"
primary = "c5cddc"
secondary = "475b84"
title = "c5cddc"
playing = "c5cddc"
playing_selected = "c5cddc"
playing_bg = "475b84"
highlight = "c5cddc"
highlight_bg = "475b84"
error = "light red"
error_bg = "1e1e1e"
statusbar = "c5cddc"
statusbar_progress = "c5cddc"
statusbar_bg = "475b84"
cmdline = "c5cddc"
cmdline_bg = "1e1e1e"
search_match = "475b84_HOVER"